language: python
python:
  - "3.2"
  - "3.3"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sudo apt-get install python3-pyqt4 python3-pyqt4.phonon"
virtualenv:
  system_site_packages: true
install: "pip install tornado requests stagger --use-mirrors"
before_script: "python test_server/server.py &"
script: py.test