language: python
python:
  - "3.2"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sudo apt-get update -qq"
  - "sudo apt-get install python3-pyqt4 python3-pyqt4.phonon"
virtualenv:
  system_site_packages: true
install: "pip install tornado requests stagger python-coveralls --use-mirrors"
before_script: "python test_server/server.py &> server.log &"
script:
  - py.test -v --cov eightplayer --cov-report term-missing
after_success:
  - coveralls